---

- hosts: "{{ node }}"
  remote_user: alexandre
  become: true
  vars:
          node_backup_dir: "/home/alexandre/couchdb_backup/backups"
          target_db: "{{ db }}"
          script_path: "/home/alexandre/couchdb_backup/couchdb-backup.sh"
          date: "{{ date }}"
  tasks:
          - name: Restore the DB on the remote node
            shell: "bash {{ script_path }} -r -H 127.0.0.1 -d {{ db }} -f {{ node_backup_dir }}/backup-{{ db }}-{{ date }}-*.json -c -u admin -p 1234"
